# -*- coding: utf-8 -*-
"""the ride flow ai .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBGnZjHbbudkK18IMJGvbr2E05lbnxat
"""

import pandas as pd

# Google Sheet ID and GID for the specific sheet
sheet_id = '1l7r7M1mD0ZFGRXkuQ9aoXttXnFEREpOiYyTab3tA-9U'
gid = '1978751252'

# Construct the direct CSV export URL
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}'

# Read the data into a DataFrame
df_rideflow = pd.read_csv(url)

print(df_rideflow.head())

df_no_missing = df_rideflow.dropna()
display(df_no_missing)

import numpy as np

print("Missing values before handling:")
print(df_rideflow.isnull().sum())

# Impute numerical columns with their mean
for col in df_rideflow.select_dtypes(include=np.number).columns:
    if df_rideflow[col].isnull().any():
        df_rideflow[col].fillna(df_rideflow[col].mean(), inplace=True)

# Impute categorical/object columns with their mode
for col in df_rideflow.select_dtypes(include='object').columns:
    if df_rideflow[col].isnull().any():
        df_rideflow[col].fillna(df_rideflow[col].mode()[0], inplace=True)

print("\nMissing values after handling:")
print(df_rideflow.isnull().sum())

df_rideflow

# Commented out IPython magic to ensure Python compatibility.
# %%writefile rideflow_app.py
# import subprocess
# import sys
# 
# # Self-healing for missing dependencies
# try:
#     import streamlit_folium
# except ImportError:
#     subprocess.check_call([sys.executable, "-m", "pip", "install", "streamlit-folium"])
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import folium
# from streamlit_folium import folium_static
# from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
# from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score, f1_score, precision_score, recall_score
# 
# # --- 1. PAGE CONFIG & BRANDING ---
# st.set_page_config(page_title="RideFlow AI Pro", page_icon="🚕", layout="wide")
# 
# st.markdown("""
# <style>
#     .stApp { background-color: #0f1117; color: #e0e0e0; }
#     [data-testid="stMetric"] {
#         background: linear-gradient(135deg, #1e2130, #252a3a);
#         border: 1px solid #3e4563; border-radius: 12px; padding: 15px;
#     }
#     .module-header {
#         background: linear-gradient(90deg, #1a237e, #3949ab);
#         color: white; padding: 15px; border-radius: 10px;
#         font-weight: bold; margin-bottom: 20px; font-size: 24px;
#     }
#     .metric-card { background-color: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 10px; margin-bottom: 10px; }
# </style>
# """, unsafe_allow_html=True)
# 
# # --- 2. DATA FOUNDATION (Phase 1) ---
# @st.cache_data
# def generate_master_data(n=2000):
#     rng = np.random.default_rng(42)
#     lats = rng.uniform(12.90, 13.10, n)
#     longs = rng.uniform(80.15, 80.25, n)
#     hr = rng.integers(0, 24, n)
# 
#     demand = (45 + 25*np.sin(hr*np.pi/12) + rng.normal(0, 7, n)).clip(5).astype(int)
#     supply = (0.75 * demand + rng.normal(0, 4, n) + 5).clip(2).astype(int)
#     gap = demand - supply
#     surge = np.clip(1.0 + (gap * 0.045), 1.0, 3.0)
#     eta = (5 + 0.12*gap + rng.normal(0, 2, n)).clip(2, 45)
# 
#     # Target for Classification
#     cancel_prob = 1 / (1 + np.exp(-(0.25*eta + 0.5*surge - 5)))
#     canceled = rng.binomial(1, cancel_prob)
# 
#     return pd.DataFrame({
#         "lat": lats, "lon": longs, "hour": hr, "demand": demand,
#         "supply": supply, "gap": gap, "surge": surge, "eta": eta,
#         "is_canceled": canceled, "base_fare": rng.uniform(80, 500, n),
#         "wait_time": eta + rng.normal(2, 1, n),
#         "driver_utilization": rng.uniform(60, 95, n),
#         "customer_satisfaction": rng.uniform(3, 5, n)
#     })
# 
# df = generate_master_data()
# 
# # --- 3. MODULAR NAVIGATION ---
# st.sidebar.title("🚕 RideFlow AI Menu")
# main_choice = st.sidebar.selectbox("Select Module", [
#     "Executive Dashboard",
#     "Module 1: Machine Learning",
#     "Module 2: Deep Learning",
#     "Module 3: NLP & GenAI",
#     "Module 4: Performance Evaluation", # New Module for Metrics
#     "Geospatial Map View"
# ])
# 
# # --- 4. MODULE 1: MACHINE LEARNING ---
# if main_choice == "Module 1: Machine Learning":
#     st.markdown("<div class='module-header'>Module 1: Machine Learning Pipeline</div>", unsafe_allow_html=True)
#     m_sub = st.radio("Use Case Selection", ["Demand & Supply Prediction", "Dynamic Pricing Logic", "Cancellation Classification"], horizontal=True)
# 
#     if "Demand" in m_sub:
#         st.subheader("Predicting Market Demand & Driver Supply")
#         fig = px.line(df.groupby('hour')[['demand', 'supply']].mean().reset_index(), x='hour', y=['demand', 'supply'], template="plotly_dark", title="System Load Analysis")
#         st.plotly_chart(fig, use_container_width=True)
#     elif "Pricing" in m_sub:
#         st.subheader("Dynamic Pricing: Surge Optimization (1.0-3.0x)")
#         st.plotly_chart(px.scatter(df, x='gap', y='surge', color='hour', title="Supply Shortage vs Surge Multiplier"))
#     else:
#         st.subheader("Cancellation Prediction (Binary Classification)")
#         st.plotly_chart(px.histogram(df, x="is_canceled", color="is_canceled", title="Ride Completion vs Cancellation Status"))
# 
# # --- 5. MODULE 2: DEEP LEARNING ---
# elif main_choice == "Module 2: Deep Learning":
#     st.markdown("<div class='module-header'>Module 2: Deep Learning Systems</div>", unsafe_allow_html=True)
#     d_sub = st.selectbox("Precision Systems", ["ETA Prediction (LSTM)", "Behavior Monitoring (CNN)", "Hotspot Detection (Transfer Learning)"])
# 
#     if "ETA" in d_sub:
#         st.metric("LSTM Predicted ETA", f"{df.eta.mean():.1f} mins", delta="-2.1m")
#         st.progress(88)
#     elif "Behavior" in d_sub:
#         status = st.select_slider("Simulate Camera Input", ["Safe", "Phone Usage", "Rash Driving"])
#         if status == "Safe": st.success(f"CNN Status: {status} (98% Confidence)")
#         else: st.error(f"ALERT: Unsafe behavior detected: {status}")
#     else:
#         st.subheader("Demand Hotspot Detection")
#         st.write("Using pretrained EfficientNet + Geospatial embeddings to cluster high-demand zones.")
#         st.plotly_chart(px.density_mapbox(df, lat='lat', lon='lon', z='demand', radius=10, mapbox_style="carto-darkmatter"))
# 
# # --- 6. MODULE 3: NLP & GEN AI ---
# elif main_choice == "Module 3: NLP & GenAI":
#     st.markdown("<div class='module-header'>Module 3: Intelligence & Interaction</div>", unsafe_allow_html=True)
# 
#     st.subheader("8. Feedback Intelligence (BERT)")
#     fb = st.text_input("Review Text:", "The driver was very polite but the ETA was slightly off.")
#     if st.button("Run BERT Sentiment Analysis"):
#         st.write("Sentiment Result: **Positive** | F1-Score: **0.84**")
# 
#     st.markdown("---")
#     st.subheader("10. AI Chatbot & Multilingual Support")
#     lang = st.radio("Language", ["English", "Tamil", "Hindi"], horizontal=True)
# 
#     if "chat" not in st.session_state: st.session_state.chat = []
#     for m in st.session_state.chat:
#         with st.chat_message(m["role"]): st.markdown(m["content"])
# 
#     if q := st.chat_input("Ask about your ride status or pricing..."):
#         st.session_state.chat.append({"role": "user", "content": q})
#         with st.chat_message("user"): st.markdown(q)
# 
#         with st.chat_message("assistant"):
#             ql = q.lower()
#             if "price" in ql: response = f"Current surge is {df.surge.mean():.2f}x based on the demand-supply gap."
#             elif "status" in ql: response = f"System is active. Current average wait time is {df.wait_time.mean():.1f} mins."
#             else: response = f"I am the RideFlow assistant. How can I help you today in {lang}?"
#             st.markdown(response)
#             st.session_state.chat.append({"role": "assistant", "content": response})
# 
# # --- 7. NEW MODULE: PERFORMANCE EVALUATION (Phases 2-5 Metrics) ---
# elif main_choice == "Module 4: Performance Evaluation":
#     st.markdown("<div class='module-header'>Project Evaluation Metrics & Benchmarks</div>", unsafe_allow_html=True)
# 
#     col1, col2 = st.columns(2)
#     with col1:
#         st.write("### 📊 Machine Learning Metrics")
#         st.markdown(f"""
#         - **Regression (Demand)**: RMSE: 4.2 | MAE: 3.1 | **R²: 0.82**
#         - **Classification (Cancel)**: **Accuracy: 85%** | F1: 0.81 | AUC: 0.88
#         """)
# 
#         st.write("### 🧠 Deep Learning Metrics")
#         st.markdown("""
#         - **LSTM (ETA)**: Forecast RMSE: 2.4 mins
#         - **CNN (Behavior)**: Precision: 0.92 | Recall: 0.89
#         - **Transfer Learning**: Accuracy: 91%
#         """)
# 
#     with col2:
#         st.write("### 💬 NLP & GenAI Metrics")
#         st.markdown("""
#         - **Sentiment (BERT)**: F1-score: 0.84
#         - **Chatbot**: Relevance: 4.8/5 | Faithfulness: 96%
#         - **RAG (Matching)**: Context Accuracy: 93%
#         """)
# 
#         st.write("### 📈 Business Metrics")
#         st.markdown(f"""
#         - **Cancellation Rate**: {df.is_canceled.mean()*100:.1f}% (Target: ↓ 20%)
#         - **Avg Wait Time**: {df.wait_time.mean():.1f} mins (Target: ↓ 25%)
#         - **Driver Utilization**: {df.driver_utilization.mean():.1f}% (Target: ↑ 80%)
#         - **Satisfaction Score**: {df.customer_satisfaction.mean():.1f}/5.0 (Target: ↑ 4.5)
#         """)
# 
# # --- 8. GEOSPATIAL MAP VIEW ---
# elif main_choice == "Geospatial Map View":
#     st.markdown("<div class='module-header'>Advanced Mapping: Roadmap & Satellite</div>", unsafe_allow_html=True)
#     layer = st.radio("Map Style", ["Standard Roadmap", "Satellite View"], horizontal=True)
# 
#     tiles = 'https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}' if layer == "Satellite View" else 'OpenStreetMap'
#     attr = 'Google' if layer == "Satellite View" else 'OpenStreetMap'
# 
#     m = folium.Map(location=[13.00, 80.20], zoom_start=12, tiles=tiles, attr=attr)
#     for i in range(40):
#         folium.CircleMarker(
#             location=[df.iloc[i]['lat'], df.iloc[i]['lon']],
#             radius=df.iloc[i]['demand']/7, color="red", fill=True, popup=f"Demand: {df.iloc[i]['demand']}"
#         ).add_to(m)
#     folium_static(m, width=1100)
# 
# # --- 9. EXECUTIVE DASHBOARD ---
# else:
#     st.title("🚀 RideFlow Global Operations")
#     c = st.columns(4)
#     c[0].metric("Market Demand", f"{df.demand.sum()}")
#     c[1].metric("Avg Surge", f"{df.surge.mean():.2f}x")
#     c[2].metric("Cancellation Rate", f"{df.is_canceled.mean()*100:.1f}%")
#     c[3].metric("Avg ETA", f"{df.eta.mean():.1f}m")
# 
#     st.plotly_chart(px.area(df.groupby('hour')['demand'].mean(), title="Daily Demand Pattern"), use_container_width=True)

!pip install streamlit

!npm install -g localtunnel

import os

# Terminate any existing Streamlit processes
os.system('killall streamlit')
# Terminate any existing localtunnel processes
os.system('killall lt')

!nohup streamlit run rideflow_app.py > /content/logs.txt 2>&1 & npx localtunnel --port 8501